export const sentencePools = {
    idle: [
        'The omens have yet to be cast… patience, traveler.',
        'The winds whisper secrets, but not yet for you.',
        'The winds are quiet… unlike my stomach.',
        'The elements are in flux; wait a moment longer.',
        'The heavens are veiled… or perhaps I forgot to open the window.',
        'The spirits are restless… as am I before my morning tea.',
        'My staff hums, awaiting the call of the skies.',
    ],
    loading: [
        'Peering into the mists of time… the truth shall soon be revealed.',
        'Consulting the ancient scrolls… the prophecy unfolds.',
        'Aligning the stars… the future is almost clear.',
        'The clouds shift, and so does my back. Ow.',
        'I summon visions from the ether… hold steady.',
        'The omens gather… slower than my old knees.',
        'The elements stir… and so does my coffee.',
    ],
    sunny: [
        'The sun shines bright, a golden orb of warmth and light.',
        'Clear skies above, a perfect day to bask in the sun’s embrace.',
        'The heavens smile — though my forehead does not. Too much sunburn.',
        'A radiant day, where every ray of sunshine feels like a gentle hug.',
        'The sun’s brilliance lights up the world, a beacon of hope and joy.',
        'A day kissed by the sun, where every moment feels like a celebration of light.',
        'No shadow lingers, except the one under my favorite nap tree.',
    ],
    rainy: [
        'The skies weep, and the earth shall drink deeply.',
        'Raindrops dance upon the ground, a symphony of nature’s tears.',
        'A gentle rain falls, washing away the dust of yesterday.',
        'The heavens open, a curtain of rain that refreshes the soul.',
        'Dark clouds churn — perfect weather for soup.',
        'The rain’s embrace is a soothing balm, a lullaby for the weary.',
        'The heavens open, and so does the leak in my hut.',
    ],
    cloudy: [
        'Clouds gather, a soft blanket over the world’s shoulders.',
        'The sky is a canvas of gray, a quiet prelude to the storm.',
        'The sun hides, cloaked in a shroud of grey.',
        'A day of muted light, where shadows play hide and seek.',
        'The sky is heavy… just like my eyelids after lunch.',
        'The clouds drift lazily, a slow dance across the heavens.',
        'The light wanes, but at least it hides my bald spot.',
    ],
    snowy: [
        'Snowflakes fall, a delicate dance of winter’s breath.',
        'Snow falls gently… unlike me when I slipped this morning.',
        'The air is crisp, and the snow crunches underfoot like nature’s confetti.',
        'A day wrapped in snow, where every flake tells a story of winter’s magic.',
        'Verily, the sky scatters its cold blessings… and I can no longer feel my toes.',
        'The air bites, crisp and clean… but mostly just bites.',
        'The land sleeps under a frozen blanket — I envy its rest.',
    ],
    error: [
        'Alas! The fates are confused, and so am I.',
        'The omens are unclear… or perhaps my crystal ball is just dirty.',
        'The stars are misaligned, and so is my sense of direction.',
        'A mysterious error has occurred… much like my last attempt at cooking.',
        'The elements are in turmoil, and so is my patience.',
        'The prophecy is lost in translation… or maybe I just need glasses.',
        'The winds of fate are fickle, and so is my internet connection.',
    ],
}
